### ISSUE TITLE
Document which version of Linux (on ODroid) is recommended

### ISSUE THREAD

**Issue by rseward** [robotpy/roborio-docker#2]
Does this project run on a particular version of Linux on the ODroid (debian?)

Also can this be used to run WPILib and simulate a networktable (E.g. robot when away from the robotics lab?)

Thanks,
Rob

**Comment by virtuald** [comment]
The only requirement is having docker installed.

I haven't tried it, but I don't believe it can be used to run roborio-native WPILib, as it requires the NI FPGA to do its things. If you're interested in that, there's a vaguely documented simulated HAL available for C++/Java. For an example project that uses that interface (I think), see the [snobot simulator](https://github.com/pjreiniger/SnobotSim).

If your robot is programmed in Python using RobotPy, you can run the [included simulator](http://robotpy.readthedocs.io/en/stable/guide/simulator.html) on Linux, Windows, and OSX.

If you want to just simulate the NetworkTables interface programatically, then use the OutlineViewer that is distributed by FIRST (see the 'WPILib' menu in Eclipse) and run it in server mode. Additionally, you can create a program that uses ntcore and run it in server mode. For a python example of this that uses pynetworktables, see [this example](https://github.com/robotpy/pynetworktables/blob/master/samples/nt_robot.py).
